"""remove_preview_image_path_from_documents

Revision ID: 756f4026693f
Revises: b0523a473e38
Create Date: 2025-11-22 14:54:52.947930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756f4026693f'
down_revision: Union[str, None] = 'b0523a473e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('preview_image_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_image_path', sa.VARCHAR(length=1024), nullable=True))

    # ### end Alembic commands ###
