"""Add preview_image_path to documents

Revision ID: b0523a473e38
Revises: 08ad2dba9bd6
Create Date: 2025-11-22 12:17:54.798277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0523a473e38'
down_revision: Union[str, None] = '08ad2dba9bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_image_path', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('preview_image_path')

    # ### end Alembic commands ###
